version: '3.8'

services:
  mongo:
    image: mongo:4.4.10
    ports:
      - "27017:27017"
    profiles:
      - "dev"
    restart: always
  redis:
    image: redis
    ports:
      - "6379:6379"
    restart: always
