version: "3.7"

services:
  db:
    image: postgres:13.3
    restart: always
    environment:
      - POSTGRES_DB=starsOfEternity
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - TZ=America/Sao_Paulo
    ports:
      - "5432:5432"
