version: '3.8'

services:
  mysql:
    image: mysql:8.0.27
    environment:
      MYSQL_ROOT_PASSWORD: secure_password
      MYSQL_DATABASE: starsOfEternity
    ports:
      - "3306:3306"
    restart: always
