name: CI

on:
  pull_request:
  push:
    branches:
      - main

env:
  IMAGE_TAG: ${{ github.event_name == 'push' && 'ayayem/stars-of-eternity-bot' || 'ghcr.io/ayayem/stars-of-eternity-bot' }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.IMAGE_TAG }}
          tags: |
            type=ref,event=pr,prefix=${{ github.head_ref }}-
            type=sha
      - name: Login to DockerHub
        if: ${{ github.event_name == 'push' }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          cache-from: type=registry,ref=${{ steps.meta.outputs.tags }}-cache
          cache-to: type=registry,ref=${{ steps.meta.outputs.tags }}-cache
          tags: ${{ steps.meta.outputs.tags }}
  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.IMAGE_TAG }}
          tags: |
            type=ref,event=pr,prefix=${{ github.head_ref }}-
            type=sha
      - name: Run linter
        run: docker container run --rm ${{ steps.meta.outputs.tags }} npm run lint
