name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - run: mkdir /tmp/stars-of-eternity-bot
      - name: Build and output
        uses: docker/build-push-action@v2
        with:
          context: .
          cache-from: type=registry,ref=ayayem/stars-of-eternity-bot:latest
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          outputs: type=docker,dest=/tmp/stars-of-eternity-bot/image.tar
      - name: Cache build
        uses: actions/cache@v2
        with:
          path: /tmp/stars-of-eternity-bot
          key: ${{ runner.os }}-stars-of-eternity-image
  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache build
        uses: actions/cache@v2
        with:
          path: /tmp/stars-of-eternity-bot
          key: ${{ runner.os }}-stars-of-eternity-image
      - name: Load image
        run: docker image load --input /tmp/stars-of-eternity-bot/image.tar
      - name: Run linter
        run: "docker container run -it --rm stars-of-eternity-bot:latest npm run lint"
  publish:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    needs: [build, lint]
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v1
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ayayem/stars-of-eternity-bot
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: stars-of-eternity-image
          path: /tmp/stars-of-eternity-bot.tar
      - name: Load image
        run: docker image load --input /tmp/stars-of-eternity-bot.tar
      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
