name: Docker CI

on:
  pull_request:
  push:
    branches:
      - main

env:
  IMAGE: ayayem/stars-of-eternity-bot
  TAG: ${{ github.event_name == 'pull_request' && format('{0}-{1}', github.head_ref, github.event.number) || github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up extra env variables
        run: |
          echo "IMAGE_TAG=$IMAGE:$TAG" >> $GITHUB_ENV
          echo "GHCR_IMAGE=ghcr.io/$IMAGE:$TAG" >> $GITHUB_ENV
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          cache-from: type=registry,ref=${{ env.GHCR_IMAGE }}-cache
          cache-to: type=registry,ref=${{ env.GHCR_IMAGE }}-cache
          tags: ${{ env.GHCR_IMAGE }}
  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set up extra env variables
        run: |
          echo "IMAGE_TAG=$IMAGE:$TAG" >> $GITHUB_ENV
          echo "GHCR_IMAGE=ghcr.io/$IMAGE:$TAG" >> $GITHUB_ENV
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Run linter
        run: docker container run --rm ${{ env.GHCR_IMAGE }} npm run lint
  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set up extra env variables
        run: |
          echo "IMAGE_TAG=$IMAGE:$TAG" >> $GITHUB_ENV
          echo "GHCR_IMAGE=ghcr.io/$IMAGE:$TAG" >> $GITHUB_ENV
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to DockerHub
        if: ${{ github.event_name == 'push' }}
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Pull image
        run: docker image pull ${{ env.GHCR_IMAGE }}
      - name: Publish to docker
        if: ${{ github.event_name == 'push' }}
        run: |
          docker image tag ${{ env.GHCR_IMAGE }} ${{ env.IMAGE_TAG }}
          docker image tag ${{ env.GHCR_IMAGE }} ${{ env.IMAGE }}:latest
          docker image push -a ${{ env.IMAGE }}
      - name: Publish to ghcr
        run: |
          docker image tag ${{ env.GHCR_IMAGE }} ghcr.io/${{ env.IMAGE }}:latest
          docker image push ghcr.io/${{ env.IMAGE }}:latest

